# Generated by Django 5.0.4 on 2024-10-23 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
